# Generated by Django 4.2.1 on 2023-07-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quienes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaProd',
            new_name='Colma2',
        ),
    ]
