# Generated by Django 4.2.1 on 2023-07-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evento',
            new_name='Galeria',
        ),
    ]
